package io.zahori.tms.alm.restclient.infrastructure;

/*-
 * #%L
 * alm-rest-client
 * $Id:$
 * $HeadURL:$
 * %%
 * Copyright (C) 2021 PANEL SISTEMAS INFORMATICOS,S.L
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB)
//Reference Implementation, vhudson-jaxb-ri-2.1-456
//See http://www.oracle.com/technetwork/articles/javase/index-140168.html
//Any modifications to this file will be lost upon recompilation of the
//source schema.
//Generated on: 2010.05.31 at 03:35:17 PM IDT
//

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Java class for anonymous complex type.
 *
 * 
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <complexType> <complexContent> <restriction base=
 * "{http://www.w3.org/2001/XMLSchema}anyType"> <sequence> <element ref=
 * "{}Attribute" maxOccurs="unbounded" minOccurs="0"/> </sequence>
 * </restriction> </complexContent> </complexType>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "attribute" })
@XmlRootElement(name = "Attributes")
public class Attributes {

	@XmlElement(name = "Attribute")
	protected List<Attribute> attribute;

	/**
	 * Gets the value of the attribute property.
	 *
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the attribute property.
	 *
	 * For example, to add a new item, do as follows:
	 *
	 * getAttribute().add(newItem);
	 *
	 * Objects of the following type(s) are allowed in the list
	 * {@link Attribute }
	 *
	 *
	 */
	public List<Attribute> getAttribute() {
		if (attribute == null) {
			attribute = new ArrayList<Attribute>();
		}
		return this.attribute;
	}

}
